service: qiita-api-scratchpad-api

plugins:
  - serverless-domain-manager
  - serverless-offline

custom:
  defaultStage: dev
  customDomain:
    domainName: ${self:custom.env.${self:provider.stage}.DOMAIN}
    basePath: ''
    stage: prod
    createRoute53Record: true
  env:
    dev: ${file(./conf.dev.yml)}
    prod: ${file(./conf.prod.yml)}

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}
  logRetentionInDays: 14
  environment:
    CLIENT_ID: ${self:custom.env.${self:provider.stage}.QIITA_CLIENT_ID}
    CLIENT_SECRET: ${self:custom.env.${self:provider.stage}.QIITA_CLIENT_SECRET}

functions:
  rpc:
    handler: dist/adapters/lambda/rpc/handlers/rpc-handler.rpc
    events:
      - http:
          path: rpc
          method: post
          cors: true
  authorize:
    handler: dist/adapters/lambda/rest/handlers/qiita-handler.authorize
    events:
      - http:
          path: authorize
          method: get

