service: qiita-api-client

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    CLIENT_ID: ${env:QIITA_CLIENT_ID}

functions:
  hello:
    handler: build/adapters/http/handlers/hello-handler.hello
    events:
      - http:
          path: hello
          method: get
  callApi:
    handler: build/adapters/http/handlers/qiita-handler.callApi
    events:
      - http:
          path: qiita/api
          method: post
          cors: true
  authorize:
    handler: build/adapters/http/handlers/qiita-handler.authorize
    events:
      - http:
          path: qiita/authorize
          method: get


